# SPDX-FileCopyrightText: 2025 SecPal Contributors
# SPDX-License-Identifier: CC0-1.0

# markdownlint-cli2 configuration
# https://github.com/DavidAnson/markdownlint-cli2

# Ignore vendor directory and node_modules
# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: CC0-1.0

# Markdownlint configuration for SecPal
# Excludes node_modules directory from linting

ignores:
  - "node_modules/**"
  - node_modules/**
  - .git/**
