# SPDX-FileCopyrightText: 2025 SecPal
# SPDX-License-Identifier: CC0-1.0

version = 1
SPDX-FileCopyrightText = "SecPal Contributors"

[[annotations]]
path = "src/**"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "public/**"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = "package.json"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "package-lock.json"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "tsconfig*.json"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "vite.config.ts"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".prettierrc.json"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".prettierignore"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".gitignore"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "README.md"
SPDX-FileCopyrightText = "2025 SecPal"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".github/**"
SPDX-FileCopyrightText = "2025 SecPal"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "CHANGELOG.md"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".markdownlint*.json"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = ".markdownlintignore"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = "scripts/**"
SPDX-FileCopyrightText = "2025 SecPal Contributors"
SPDX-License-Identifier = "MIT"
